### ISSUE TITLE
TPM2_Load response too short?

### ISSUE THREAD

**Issue by jezzab** [kkamagui/bitleaker#9]
Everything appears to be working beautifully but the data seems to be a lot shorter than the other logs I have seen which is causing it to fail. The unit is a NUC using Intel PTT

![Capture](https://user-images.githubusercontent.com/4190429/128276645-21f54f17-09c2-4f30-9063-58805ffae3cc.JPG)

Any ideas would be greatly appreciated

**Comment by kkamagui** [comment]
Hello @jezzab,

It seems that there is no 81000001h handle in your Intel PTT. Did you enable BitLocker with UEFI Secureboot?

Best regards,

Seunghun

**Comment by jezzab** [comment]
I assume it was enabled with it Secure Boot turned off as its off now and booting into Windows with Bitlocker enabled
![Capture](https://user-images.githubusercontent.com/4190429/128290107-463e55f8-fff5-4dbb-b737-af59c9648ce6.JPG)

**Comment by jezzab** [comment]
What would cause it not to be able to read the 0x81000001 handle? Is there something I can look into to try and work out what is going on?

Appreciate your help
Jeremy

**Comment by kkamagui** [comment]
Hi @jezzab, you can read 0x81000001 with the command below.
```bash
$> tpm2_readpublic -c 0x81000001
```

By the way, it's a weird case. If you don't mind, would you share the kernel log after my BitLeaker runs? You can get the kernel log with the below command.
```bash
# If you share the log, I will check what happened.
$> sudo dmesg > kernel_log.txt
```

Best regards,

Seunghun

**Comment by jezzab** [comment]
Thanks for the reply @kkamagui
Im having issues with the `tpm2_readpublic -c 0x81000001`
![Capture](https://user-images.githubusercontent.com/4190429/128674835-d21bc478-d05e-4079-8ebf-28e59b8957cb.JPG)

But here is the kernel log
[kernel_log.txt](https://github.com/kkamagui/bitleaker/files/6952798/kernel_log.txt)

**Comment by jezzab** [comment]
```
jez@jez-NUC7i3DNB:$ sudo ./tpm2_readpublic -c 0x81000001 -o output_pubkey.txt -f pem -t primary.handle
name: 000bbb09152e398fd61af41715e3e67912624edce7ceffcb7ba1691dcc605600d8fc
qualified name: 000b43fec5cb008a56290a130a00203b97704c55db592758fe6554af4451a85c6b3b
name-alg:
  value: sha256
  raw: 0xb
attributes:
  value: fixedtpm|fixedparent|sensitivedataorigin|userwithauth|noda|restricted|decrypt
  raw: 0x30472
type:
  value: rsa
  raw: 0x1
exponent: 65537
bits: 2048
scheme:
  value: null
  raw: 0x10
scheme-halg:
  value: (null)
  raw: 0x0
sym-alg:
  value: aes
  raw: 0x6
sym-mode:
  value: cfb
  raw: 0x43
sym-keybits: 128
rsa: c6339de2abf69406cd98b98d774ce31d69cfe06fd0d9edeed3a4f0f9586a879752c506bce52760770818336fc3be2f7f33b8b681b04b4626f47d272f75119034c4c2fb290f8c133ed1194df786ebdee21f2fc9529466db78d015797e17445ff5a6d7f06ecb4d5ea740de2ef64a85531725c15771201a4876701fa2f316d944121d961d722733b004fb274825876b508d152c916b30b4301bb273f75d79ba29daf466d08786b1f1eecb1a07e2660e0d5603a6ad111a975e76cc2daec7415dde4032053baf8a769021d4e5feb266b5edd45de98ff156166305d311ad7db3c98db2505a0ae013e6466a6ab212c1e2dd7804979dbd6a516055641e75b1a7b07d1f55
```
[output_pubkey.txt](https://github.com/kkamagui/bitleaker/files/6957688/output_pubkey.txt)
[output_raw.zip](https://github.com/kkamagui/bitleaker/files/6957709/output_raw.zip)
